package lt.vu.mif.knygynas.mybatis.model;

import java.util.List;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @return the value of PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.NAME
     *
     * @param name the value for PUBLIC.AUTHOR.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    // Added by hand
    private List<Book> books;

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    public List<Book> getBooks() {
        return books;
    }
}