package lt.vu.mif.knygynas.mybatis.model;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @return the value of PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @param id the value for PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @return the value of PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @param name the value for PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Wed Apr 04 00:05:11 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}